/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Nathang30 (https://sketchfab.com/Nathang30)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/lucifer-morningstar-f840410d898f4821861315ec9dfe52c1
title: Lucifer Morningstar
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/models/lucifer_morningstar/scene.gltf');
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['Material.004']} />
        <lineSegments geometry={nodes.Object_5.geometry} material={materials['material_0.002']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['material_0.002']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['Material.001']} />
      </group>
    </group>
  );
}

useGLTF.preload('/models/lucifer_morningstar/scene.gltf');
